// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV7Wa2hwQ-ZDuLGpHTafS6xITY9MzOpf4',
    appId: '1:182417883732:web:170bdc995be41e479463c1',
    messagingSenderId: '182417883732',
    projectId: 'synovia-ai-telehealth',
    authDomain: 'synovia-ai-telehealth.firebaseapp.com',
    storageBucket: 'synovia-ai-telehealth.firebasestorage.app',
    measurementId: 'G-XLJVWZYN8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBmtVR0nAAkzqcLwOOwFK1iMKQpR-eZ7M',
    appId: '1:182417883732:android:cea7e341914b2a7c9463c1',
    messagingSenderId: '182417883732',
    projectId: 'synovia-ai-telehealth',
    storageBucket: 'synovia-ai-telehealth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGyKJCo4buV5ScGw05s253_DVlUj4umWY',
    appId: '1:182417883732:ios:e6ecfd1e12fe78249463c1',
    messagingSenderId: '182417883732',
    projectId: 'synovia-ai-telehealth',
    storageBucket: 'synovia-ai-telehealth.firebasestorage.app',
    iosBundleId: 'com.example.synoviaAiTelehealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGyKJCo4buV5ScGw05s253_DVlUj4umWY',
    appId: '1:182417883732:ios:e6ecfd1e12fe78249463c1',
    messagingSenderId: '182417883732',
    projectId: 'synovia-ai-telehealth',
    storageBucket: 'synovia-ai-telehealth.firebasestorage.app',
    iosBundleId: 'com.example.synoviaAiTelehealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV7Wa2hwQ-ZDuLGpHTafS6xITY9MzOpf4',
    appId: '1:182417883732:web:9d5004c79b75cd539463c1',
    messagingSenderId: '182417883732',
    projectId: 'synovia-ai-telehealth',
    authDomain: 'synovia-ai-telehealth.firebaseapp.com',
    storageBucket: 'synovia-ai-telehealth.firebasestorage.app',
    measurementId: 'G-X3345Y3EHW',
  );
}
